import { createClient } from "@supabase/supabase-js";
import cookieParser from "cookie-parser";
import cors from "cors";
import express from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import pinoHttp from "pino-http";
import authRoutes from "./auth/auth.routes";
import { logger } from "./logger";
import adminProjectsRoutes from "./projects/projects.routes";

const app = express();

app.use(pinoHttp({ logger }));

/* security & parsers */
app.use(helmet());
app.use(express.json());
app.use(cookieParser());

/* CORS*/
app.use(
	cors({
		origin: "http://localhost:5173",
		credentials: true,
	}),
);

app.use(
	rateLimit({
		windowMs: 15 * 60 * 1000,
		max: 200,
	}),
);

app.get("/", (_req, res) => {
	res.json({ message: "Welcome to my Portfolio API" });
});

/* health */
app.get("/health", (_req, res) => {
	res.json({ ok: true });
});

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseServiceRoleKey) {
	throw new Error("Missing required Supabase environment variables");
}

const supabase = createClient(supabaseUrl, supabaseServiceRoleKey);

/* public */
app.get("/projects", async (_req, res) => {
	try {
		const { data, error } = await supabase
			.from("projects")
			.select("*")
			.order("created_at", { ascending: false });

		console.log(data);
		if (error) {
			logger.error(error, "Error fetching projects from Supabase");
			return res.status(500).json({ error: "Failed to fetch projects" });
		}

		return res.json({ projects: data, count: data.length });
	} catch (error) {
		logger.error(error, "Unexpected error fetching projects");
		return res
			.status(500)
			.json({ error: "Unexpected error fetching projects" });
	}
});

app.post("/projects", async (req, res) => {
	const { title, description, image_url, github_url, live_url, tags } =
		req.body;

	if (!title) return res.status(400).json({ error: "title is required" });

	const { data, error } = await supabase
		.from("projects")
		.insert([{ title, description, image_url, github_url, live_url, tags }])
		.select()
		.single();

	if (error) return res.status(500).json({ error: error.message });

	// data includes id + created_at generated by DB
	return res.status(201).json(data);
});

/* auth + admin */
app.use("/auth", authRoutes);
app.use("/admin/projects", adminProjectsRoutes);

export default app;
